# Generated by Django 3.0.4 on 2020-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200325_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
    ]
