# Generated by Django 3.0.4 on 2020-04-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
